name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Clonar el repositorio
    - name: Checkout repo
      uses: actions/checkout@v3

    # 2️⃣ Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3️⃣ Instalar dependencias
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 4️⃣ Instalar Jest globalmente para evitar permisos
    - name: Install Jest globally
      run: npm install -g jest

    # 5️⃣ Ejecutar pruebas unitarias
    - name: Run tests
      run: jest

    # 6️⃣ Login a Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7️⃣ Construir la imagen Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hola-mundo-node:latest .

    # 8️⃣ Subir la imagen a Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hola-mundo-node:latest
